### ISSUE TITLE
Missing traceback in xalt_syslog_to_db.py

### ISSUE THREAD

**Issue by ZQyou** [xalt/xalt#44]
I got this error recently
```
###############################################################
XALT Git Version: xalt-2.10.1-3-gfa56a8d
################################################################

-------+-------+-------+-------+-------|-------+-------+CommandLine: "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py" "--syshost" "owens" "--reverseMapD" "/mnt/owens/xalt/etc/reverseMapD" "--leftover" "/var/log/remote/xalt/leftover_owens.log" "--confFn" "/mnt/owens/xalt/etc/xalt_db.conf" "--syslog" "/var/log/remote/xalt/2021/04/06/owens.log"
XALT_LOGGING: run owens
run_to_db()
query:
msg:
run_to_db():  'userT'
'userT'
userDT:  {u'num_threads': 1.0, u'probability': 1.0, u'num_gpus': 0.0, u'start_time': 1617694878.4229, u'exec_epoch': 1617694878.0, u'num_cores': 1.0, u'num_nodes': 1.0, u'end_time': 1617720694.2083, u'num_tasks': 1.0, u'run_time': 25815.7854}
Traceback (most recent call last):
 File "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py", line 513, in <module>
   if ( __name__ == '__main__'): main()
 File "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py", line 492, in main
   print(traceback.format_exc())
NameError: global name 'traceback' is not defined
```

There is no `import traceback` in `xalt_syslog_to_db.py`.

**Comment by rtmclay** [comment]
Thanks for the bug report!  I have fixed my copy and this will be part of the next release.
