### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by ZQyou** [xalt/xalt#48]
We encountered this error after upgrading to 2.10.10:
```
################################################################
XALT Git Version: xalt-2.10.10-3-g42b3703
################################################################

Traceback (most recent call last):
 File "/mnt/pitzer/xalt/xalt/sbin/xalt_syslog_to_db.py", line 532, in <module>
   if ( __name__ == '__main__'): main()
 File "/mnt/pitzer/xalt/xalt/sbin/xalt_syslog_to_db.py", line 464, in main
   print("xalt_syslog_to_db: Error: %s %s" % (e.args[0], e.args[1]))
IndexError: tuple index out of range
```
It happened within 4 secs as the script started.

This is full traceback of the exception we are hitting:
```
xalt_syslog_to_db: Error: 'nb'
Traceback (most recent call last):
  File "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py", line 462, in main
    t, done = parseSyslog.parse(line, args.syshost, old)
  File "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py", line 226, in parse
    return self.__parseSyslog(version, s, clusterName, old)
  File "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py", line 297, in __parseSyslog
    r            = Record(t, old)
  File "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py", line 120, in __init__
    nblks          = int(t['nb'])
KeyError: 'nb'
```

Here is the entry  when KeyError is hit:
```
{'kind': 'run', 'crcStr': 'nb', 'syshost': 'owens', '37': 'idx', 'value': 'LIA/EstProducts/linux_a64:/usr/local/abaqus/2020/SIMULIA/EstProducts/linux_a64/code:/usr/local/abaqus/2020/SIMULIA/EstProducts/linux_a64/code/bin:/usr/local/abaqus/2020/SIMULIA/EstProducts/linux_a64/code/bin/SMAExternal:/usr/local/abaqus/2020/SIMULIA/EstProducts/linux_a64/CAEresources:/usr/local/abaqus/2020/SIMULIA/EstProducts/linux_a64/SMA:/usr/local/abaqus/2020/SIMULIA/EstProducts/linux_a64/code/python2.7/lib:/usr/local/abaqus/2020/SIMULIA/EstProducts/linux_a64/tools/SMApy/python2.7/lib:/usr/local/abaqus/', 'version': 4, 'key': '_run_strt_c241b974-2d84-4d58-a09c-1cf9e3c7a3c7'}
```

We currently bypass this error with a local change to the script:
```
--- xalt_syslog_to_db.py.orig   2021-05-20 15:48:00.762927000 -0400
+++ xalt_syslog_to_db.py        2021-05-24 16:59:16.394879000 -0400
@@ -461,7 +461,7 @@
       try:
         t, done = parseSyslog.parse(line, args.syshost, old)
       except Exception as e:
-        print("xalt_syslog_to_db: Error: %s %s" % (e.args[0], e.args[1]))
+        print("xalt_syslog_to_db: Error: %s" % str(e))
         badsyslog += 1
         continue
```

We are looking for a permanent fix so the change we made will not be lost after upgrading. Thank you.

**Comment by rtmclay** [comment]
It would be a great help if you could collect all of the syslog records for this failure for key: run_strt_c241b974-2d84-4d58-a09c-1cf9e3c7a3c7'.  I need to test the failure when processing the syslog in both python 2 and 3.

**Comment by ZQyou** [comment]
Here is the data: https://osu.box.com/s/4131te10309wjpqbxk719qmab9so569z. The link will expire in 30 days.

**Comment by rtmclay** [comment]
Thanks very much for the XALT records from your syslog output.  I was able to reproduce your issue and fix it. Please test the new version (xalt-2.10.11) to see if it works for you.

**Comment by ZQyou** [comment]
Thanks for the fix. We are able to complete ingest even with an error:

```
[1]
xalt_syslog_to_db: Error: 'nb'
Traceback (most recent call last):
  File "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py", line 470, in main
    t, done = parseSyslog.parse(line, args.syshost, old)
  File "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py", line 231, in parse
    return self.__parseSyslog(version, s, clusterName, old)
  File "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py", line 305, in __parseSyslog
    r            = Record(t, old)
  File "/mnt/owens/xalt/xalt/sbin/xalt_syslog_to_db.py", line 120, in __init__
    nblks          = int(t['nb'])
KeyError: 'nb'
```

We probably miss just some jobs/entries.

**Comment by ZQyou** [comment]
It went worse with this fix.  I tested 2.10.11 and 2.10.14, and only got few entries into the database.  It works fine with 2.10.10 if I don't get index error. Here is the test log: https://raw.githubusercontent.com/ZQyou/xalt_test/main/2021/pitzer/pitzer_20210610_h1000.log

**Comment by ZQyou** [comment]
I also cannot ingest the log file generated with XALT >= 2.10.11 with 2.10.10 due the format change. I start losing tracking records and really need a fix asap. Thanks.

**Comment by rtmclay** [comment]
I am looking at the pitzer log file you sent me.  I see that I am recording less entries are being ingested than generated.  I don't have a fix yet.  I just want to make sure that you are seeing the same issue that I am.

**Comment by ZQyou** [comment]
The pitzer log file is generated with XALT 2.10.10. This is the ingest output with 2.10.11
```
python2 /users/PZS0710/zyou/opt/xalt/2.10.11-syslog/sbin/xalt_syslog_to_db.py --syshost pitzer --reverseMapD /fs/ess/PZS0710/xalt/etc/pitzer/reverseMapD --confFn /fs/ess/PZS0710/xalt/etc/pitzer/xalt_db.conf --syslog pitzer_20210610_h1000.log

################################################################
XALT Git Version: XALT 2.10.11
################################################################

-------------------+---------------------+--------------------+---------------------+--------------------|---------------------+---------------------+--------------------+---------------------+--------------------
total processed :  672443 , num links:  0 , num runs:  0 , pkgCnt:  0 , badCnt:  0 , badsyslog:  0
```

With 2.10.10
```
 python2 /users/PZS0710/zyou/opt/xalt/2.10.10-syslog/sbin/xalt_syslog_to_db.py --syshost pitzer --reverseMapD /fs/ess/PZS0710/xalt/etc/pitzer/reverseMapD --confFn /fs/ess/PZS0710/xalt/etc/pitzer/xalt_db.conf --syslog pitzer_20210610_h1000.log

################################################################
XALT Git Version: XALT 2.10.10
################################################################

-------------------+---------------------+--------------------+---------------------+--------------------|---------------------+---------------------+--------------------+---------------------+--------------------
total processed :  1307886 , num links:  0 , num runs:  39 , pkgCnt:  0 , badCnt:  0 , badsyslog:  0
```

Run twice with 2.10.14  due to traceback error
```
python2 /users/PZS0710/zyou/opt/xalt/2.10.14-syslog/sbin/xalt_syslog_to_db.py --syshost pitzer --reverseMapD /fs/ess/PZS0710/xalt/etc/pitzer/reverseMapD --confFn /fs/ess/PZS0710/xalt/etc/pitzer/xalt_db.conf --syslog pitzer_20210610_h1000.log

################################################################
XALT Git Version: XALT 2.10.14
################################################################

xalt_syslog_to_db: Error: 'nb'
Traceback (most recent call last):
  File "/users/PZS0710/zyou/opt/xalt/2.10.14-syslog/sbin/xalt_syslog_to_db.py", line 471, in main
    t, done = parseSyslog.parse(line, args.syshost, old)
  File "/users/PZS0710/zyou/opt/xalt/2.10.14-syslog/sbin/xalt_syslog_to_db.py", line 231, in parse
    return self.__parseSyslog(version, s, clusterName, old)
  File "/users/PZS0710/zyou/opt/xalt/2.10.14-syslog/sbin/xalt_syslog_to_db.py", line 305, in __parseSyslog
    r            = Record(t, old)
  File "/users/PZS0710/zyou/opt/xalt/2.10.14-syslog/sbin/xalt_syslog_to_db.py", line 120, in __init__
    nblks          = int(t['nb'])
KeyError: 'nb'

-------------------+---------------------+--------------------+---------------------+--------------------|---------------------+---------------------+--------------------+---------------------+--------------------
total processed :  673080 , num links:  0 , num runs:  0 , pkgCnt:  0 , badCnt:  0 , badsyslog:  1 , dups:  0

 python2 /users/PZS0710/zyou/opt/xalt/2.10.14-syslog/sbin/xalt_syslog_to_db.py --syshost pitzer --reverseMapD /fs/ess/PZS0710/xalt/etc/pitzer/reverseMapD --confFn /fs/ess/PZS0710/xalt/etc/pitzer/xalt_db.conf --syslog pitzer_20210610_h1000.log

################################################################
XALT Git Version: XALT 2.10.14
################################################################

-------------------+---------------------+--------------------+---------------------+--------------------|---------------------+---------------------+--------------------+---------------------+--------------------
total processed :  1307886 , num links:  0 , num runs:  0 , pkgCnt:  0 , badCnt:  0 , badsyslog:  0 , dups:  0
```

**Comment by rtmclay** [comment]
I created a bug in xalt-2.10.10 where the key value pairs used crc:0xABCD instead of crcStr:0xABCD.  The 2.10.10 parser expected crcStr: and did not handle crc:.  This has been fixed.  It just means that the leftover.log file generated by xalt-2.10.10 is broken and must be removed.  

There was a second bug when a syslog line contained a trailing blank.  These trailing blanks were lost, so the CRC value was wrong and that record was never recorded. 

The newest version of XALT fixes both of those bugs.  I have also tested XALT 2.10.17 reading in *.json records written to syslog with XALT-2.10.10.

Note that if you ingest the same syslog file twice you won't re-ingest any new records.  They are already stored in the database.

Please test XALT-2.10.17 with all your generated data from any version of XALT.

**Comment by ZQyou** [comment]
Thank you for the prompt fix. I tried 2.10.17  on both log files (https://github.com/ZQyou/xalt_test/tree/main/2021/pitzer) but I still don't get any record
```
+ rm -f leftover_pitzer.log
+ python2 /users/PZS0710/zyou/opt/xalt/2.10.17-syslog/sbin/xalt_syslog_to_db.py --syshost pitzer --reverseMapD /fs/ess/PZS0710/xalt/etc/pitzer/reverseMapD --leftover leftover_pitzer.log --confFn /fs/ess/PZS0710/xalt/etc/pitzer/xalt_db.conf --syslog pitzer_20210612_h1000.log

################################################################
XALT Git Version: XALT 2.10.17
################################################################

-------------------+---------------------+--------------------+---------------------+--------------------|---------------------+---------------------+--------------------+---------------------+--------------------
total processed :  659499 , num links:  0 , num runs:  0 , pkgCnt:  0 , badCnt:  0 , badsyslog:  0 , dups:  0

+ rm -f leftover_pitzer.log
+ python2 /users/PZS0710/zyou/opt/xalt/2.10.17-syslog/sbin/xalt_syslog_to_db.py --syshost pitzer --reverseMapD /fs/ess/PZS0710/xalt/etc/pitzer/reverseMapD --leftover leftover_pitzer.log --confFn /fs/ess/PZS0710/xalt/etc/pitzer/xalt_db.conf --syslog pitzer_20210610_h1000.log

################################################################
XALT Git Version: XALT 2.10.17
################################################################

-------------------+---------------------+--------------------+---------------------+--------------------|---------------------+---------------------+--------------------+---------------------+--------------------
total processed :  672443 , num links:  0 , num runs:  0 , pkgCnt:  0 , badCnt:  0 , badsyslog:  0 , dups:  0
```
All tables in test database were truncated before test.  

I also tried a full-size of log file that was generated with 2.10.10 and got only 7 entries
```
+ rm -f leftover_pitzer.log
+ python2 /users/PZS0710/zyou/opt/xalt/2.10.17-syslog/sbin/xalt_syslog_to_db.py --syshost pitzer --reverseMapD /fs/ess/PZS0710/xalt/etc/pitzer/reverseMapD --leftover leftover_pitzer.log --confFn /fs/ess/PZS0710/xalt/etc/pitzer/xalt_db.conf --syslog pitzer_20210610.log

################################################################
XALT Git Version: XALT 2.10.17
################################################################

-------------------+---------------------+--------------------+---------------------+--------------------|---------------------+---------------------+--------------------+---------------------+--------------------
total processed :  4014000895 , num links:  0 , num runs:  7 , pkgCnt:  0 , badCnt:  0 , badsyslog:  0 , dups:  0
```

**Comment by rtmclay** [comment]
I believe that the issue for you is that the crc calculation on the python side is failing.  It could be a python2 vs. python3 issue. You are using python2 and I use python3. In any event, the CRC check is not required on the python side.  The CRC is there to separate out the different records that have the same run_uuid.  

Please test xalt-2.10.18 to see if it works for you.  Thanks for sending me these issues!

**Comment by ZQyou** [comment]
Everything is working with 2.10.18. Thank you for the prompt fixing. :)  You may close this issue.

**Comment by rtmclay** [comment]
Thanks for working with me to track down all the various issues!  Closing this issue.
